### ISSUE TITLE
0.2版本运行成功，小程序界面编译、渲染正常。devtool无法加载。

### ISSUE THREAD

**Issue by zhea55** [jiyeme/wechat-devtools#2]
![devtools](https://user-images.githubusercontent.com/7816215/151295854-d2752786-bc8b-4a60-afbf-e512e6dfb00b.png)
![devtools_ip](https://user-images.githubusercontent.com/7816215/151295879-3f7b4802-d6d4-4b8f-803d-83e818659d2d.png)

devtool加载不了，看上面图片，好像是host参数配置的不对。

另外，我看你的build日志，好像有2个地方报错了，是不是需要处理一下？
![image](https://user-images.githubusercontent.com/7816215/151295970-fda319f1-b162-4d69-9c29-c4bc9f9f3b6d.png)
![image](https://user-images.githubusercontent.com/7816215/151296054-b7f7eacb-e4aa-4e0e-bbdc-582278f5667b.png)

**Comment by zhea55** [comment]
我猜测，是不是因为nwjs是用的普通版本？

https://nwjs.io/blog/v0.60.0/

> There are 2 builds for each platform - normal build, and SDK build. Normal build doesn't have devtools, only SDK build does. lt can be opened by pressing F12 (Cmd-Alt-I on OSX). SDK packages also have more development tools to be exposed in the following releases, as well as the NaCl support.

**Comment by jiyeme** [comment]
昨晚刚发现，这个调试器加载目录有点小问题
尝试修改：
`bin/wechat-devtools`中的最后一行`exec "$root_dir/nwjs/nw" $root_dir/package.nw $EXTENSION2 $INSPECTOR1 "$@"`
`$EXTENSION2 $INSPECTOR1` 这两个参数1、2换一换，4种组合，还没弄清具体原因。

**Comment by zhea55** [comment]
> 昨晚刚发现，这个调试器加载目录有点小问题 尝试修改： `bin/wechat-devtools`中的最后一行`exec "$root_dir/nwjs/nw" $root_dir/package.nw $EXTENSION2 $INSPECTOR1 "$@"` `$EXTENSION2 $INSPECTOR1` 这两个参数1、2换一换，4种组合，还没弄清具体原因。

成功了。感谢。
![image](https://user-images.githubusercontent.com/7816215/151299009-3f9b7554-031e-43a7-ba4b-ef8b51e78a2f.png)

```bash
env GDK_BACKEND=x11 ./nwjs/nw ./package.nw --custom-devtools-frontend=./package.nw/js/ideplugin/inspector --load-extension=~/.config/wechat_devtools/WeappPlugin
```

https://nwjs.io/blog/v0.50.0/

nwjs能不能升级这个版本。这个支持wayland。



另外那个用手去页面里面选取元素的功能，不知道为什么用不了。

**Comment by zhea55** [comment]
选取元素的功能不能用。

我猜测跟devtools同时加载了Elements和Wxml标签有关系。


系统不知道用鼠标选取的元素，应该使用哪个标签去捕获元素。

**Comment by jiyeme** [comment]
emm,我这边可以选中，目前问题还挺多，比如终端不能用。

**Comment by zhea55** [comment]
> emm,我这边可以选中，目前问题还挺多，比如终端不能用。

你是用的root账号吗？

根目录下所有文件和目录都是777吗？

**Comment by jiyeme** [comment]
> > emm,我这边可以选中，目前问题还挺多，比如终端不能用。
> 
> 你是用的root账号吗？
> 
> 根目录下所有文件和目录都是777吗？

普通用户，
权限都是777（刚注意到）

**Comment by jiyeme** [comment]
> > 昨晚刚发现，这个调试器加载目录有点小问题 尝试修改： `bin/wechat-devtools`中的最后一行`exec "$root_dir/nwjs/nw" $root_dir/package.nw $EXTENSION2 $INSPECTOR1 "$@"` `$EXTENSION2 $INSPECTOR1` 这两个参数1、2换一换，4种组合，还没弄清具体原因。
> 
> 成功了。感谢。 ![image](https://user-images.githubusercontent.com/7816215/151299009-3f9b7554-031e-43a7-ba4b-ef8b51e78a2f.png)
> 
> ```shell
> env GDK_BACKEND=x11 ./nwjs/nw ./package.nw --custom-devtools-frontend=./package.nw/js/ideplugin/inspector --load-extension=~/.config/wechat_devtools/WeappPlugin
> ```
> 
> https://nwjs.io/blog/v0.50.0/
> 
> nwjs能不能升级这个版本。这个支持wayland。
> 
> 另外那个用手去页面里面选取元素的功能，不知道为什么用不了。

我直接把版本升到0.53.1了；
从这个版本开始，`node`版本>=16.x。
因为大部分模块不支持 node15.x .

**Comment by jiyeme** [comment]
问题解决
